title: Alex is turning six!
email: zimolzak@fastmail.com
description: >- # this means to ignore newlines until "baseurl:"
  It's a play date in a park in Houston, on September 10, 2022.
baseurl: "/birthday-party" # the subpath of your site, e.g. /blog
url: "https://zimolzak.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb  # what happens here
github_username:  zimolzak

# Build settings
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
